routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::get('/', 'HomeController@index')->name('home');
Route::get('/details/{slug}', 'HomeController@details')->name('details');
Route::post('/comment', 'HomeController@comment')->name('comment');

Route::group(['prefix'=>'admin'],function(){
    Auth::routes();

    Route::get('/','CategoryController@index');
    Route::resource('/category', 'CategoryController',['as'=>'admin']);
    Route::resource('/post', 'PostController',['as'=>'admin']);
    Route::get('logout', 'Auth\LoginController@logout', function () {
        return abort(404);
    })->name('logout');
});

app/Category.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    public $timestamps = true;

    protected $dates = ['created_at','updated_at'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
         'title','user_id','image','slug'
    ];

    // relateion to get posts of category
    function posts(){
        return $this->hasMany('App\Post');
    }

    // relateion to get user who create ot update category
    function user(){
        return $this->belongsTo('App\User');
    }


}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Auth;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


class CategoryController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        /***
         * it's better if make it server DataTable  :)
         * and make limit from setting :)
         */
        $data = Category::with('user')
            ->orderBy('id', 'DESC')
            ->paginate(10);

        return view('admin.category.index', ['data' => $data]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate Data
        $request->validate([
            'title' => 'required|string|unique:categories|max:255',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|',
        ]);

        // uniq name for image
        $imageName = time() . uniqid() . '.' . request()->image->getClientOriginalExtension();
        request()->image->move(public_path('uploads/category'), $imageName);

        $store = Category::create([
            'title' => $request['title'],
            'user_id' => Auth::id(),
            'image' => $imageName
        ]);

        //check Query
        if ($store) {
            $store->update(['slug' => slug($request->title, $store->id)]);
            return redirect()
                ->route('admin.category.create')
                ->with('status', 'success')
                ->with('msg', 'Data has been added successfully');
        } else {
            return redirect()
                ->route('admin.category.create')
                ->with('status', 'danger')
                ->with('msg', 'Sorry Couldn\'t add ');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.category.create', ['data' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        // Validate Data
        $validation = [
            'title' => 'required|string|unique:categories,id,' . $category->id . '|max:255',
        ];

        if ($request->image) {
            $validation['image'] = 'required|image|mimes:jpeg,png,jpg,gif,svg|';
        }

        $request->validate($validation);
        if ($request->image) {
            // uniq name for image
            $imageName = time() . uniqid() . '.' . request()->image->getClientOriginalExtension();
            request()->image->move(public_path('uploads/category'), $imageName);
        }

        $data = [
            'title' => $request['title'],
            'slug' => slug($request['title'], $category->id),
            'user_id' => Auth::id(),
        ];

        if ($request->image) {
            $data['image'] = $imageName;
        }

        $update = $category->update($data);

          //check Query
        if ($update) {
            return redirect()
                ->route('admin.category.edit', $category->id)
                ->with('status', 'success')
                ->with('msg', 'Data has been Updated successfully');
        } else {
            return redirect()
                ->route('admin.category.edit', $category->id)
                ->with('status', 'danger')
                ->with('msg', 'Sorry Couldn\'t Updated');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {

        // delete comments of posts of category
        if($category->posts->isNotEmpty()){
            foreach ($category->posts as $post){
                $post->comments()->delete();
            }
        }

        // delete posts of category
        $category->posts()->delete();

        // delete category
        if ($category->delete()) {
            return ['status' => true, 'msg' => __('News has been deleted successfully')];
        } else {
            return ['status' => false, 'msg' => 'Sorry Couldn\'t Delete'];
        }
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.main')

@section('content')
    <section class="blog-area section">
        <div class="container">
    <div class="row">
        <div class="col-md-12 post-wrapper">

            @if($errors->any())
                <div class="col-sm-12">
                    <div class="card">
                        <div class="alert alert-danger">
                            {{__('Some fields are invalid please fix them')}}
                        </div>
                    </div>
                </div>
            @elseif(Session::has('status'))
                <div class="col-sm-12">
                    <div class="card">
                        <div class="alert alert-{{Session::get('status')}}">
                            {{ Session::get('msg') }}
                        </div>
                    </div>
                </div>
            @endif
            {!! Form::open(['route' => isset($data->id) ? ['admin.category.update',$data->id]:'admin.category.store','method' => isset($data->id) ?  'PATCH' : 'POST','files' => true]) !!}

                <div class="form-group col-sm-12{!! formError($errors,'title',true) !!}">
                    <div class="controls">
                        {!! Form::label('title','Title') !!}
                        {!! Form::text('title',isset($data->id) ? $data->title:old('title'),['class'=>'form-control']) !!}
                    </div>
                    {!! formError($errors,'title') !!}
                </div>

                <div class="form-group col-sm-12{!! formError($errors,'image',true) !!}">
                    <div class="controls">
                        {!! Form::label('image','Image') !!}
                        {!! Form::file('image',['class'=>'form-control']) !!}
                    </div>
                    {!! formError($errors,'image') !!}
                </div>

                @if(isset($data->id))
                    <div class="form-group col-sm-12">
                        <img style="width: 60px;height: 60px" src="{{asset('uploads/category/'.$data->image)}}" alt="">
                    </div>
                    @endif




                {!! Form::submit(__('Save'),['class'=>'btn btn-success pull-right']) !!}
                {!! Form::close() !!}


        </div>
    </div><!-- row -->
        </div><!-- container -->
    </section><!-- section -->
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.main')

@section('content')
    <section class="blog-area section">
        <div class="container">
    <div class="row">
        <div class="col-md-12 post-wrapper">
            <a href="{{route('admin.category.create')}}" class="btn btn-primary mb-2">Add New</a>
            <table class="table">
                <thead class="thead-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Image</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                @if($data->isNotEmpty())
                    @foreach($data as $row)
                        <tr>
                            <th scope="row">{{$row->id}}</th>
                            <td>{{$row->title}}</td>
                            <td><img src="{{asset('uploads/category/'.$row->image)}}" style="width: 60px;height: 60px" /></td>
                            <td>{{$row->user->name}}</td>
                            <td><a href="{{route('admin.category.edit',$row->id)}}" class="btn btn-primary"><i class="fa fa-edit" aria-hidden="true"></i></a></td>
                            <td><a href="javascript:;" onclick="deleteRecord('{{route('admin.category.destroy',$row->id)}}')" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a></td>


                        </tr>
                    @endforeach
                @else
                <tr><td colspan="4">There is no Data</td></tr>
                @endif
                </tbody>
            </table>
            {{ $data->links() }}

        </div>
    </div><!-- row -->
        </div><!-- container -->
    </section><!-- section -->
@endsection