routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::get('/', 'HomeController@index')->name('home');
Route::get('/details/{slug}', 'HomeController@details')->name('details');
Route::post('/comment', 'HomeController@comment')->name('comment');

Route::group(['prefix'=>'admin'],function(){
    Auth::routes();

    Route::get('/','CategoryController@index');
    Route::resource('/category', 'CategoryController',['as'=>'admin']);
    Route::resource('/post', 'PostController',['as'=>'admin']);
    Route::get('logout', 'Auth\LoginController@logout', function () {
        return abort(404);
    })->name('logout');
});

app/Post.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Post extends Model
{
    use SoftDeletes;
    public $timestamps = true;

    protected $dates = ['created_at','updated_at'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_id', 'title', 'content','user_id','image','slug'
    ];

    // relateion to get comments of post
    function comments(){
        return $this->hasMany('App\Comment');
    }

    // relateion to get category of post
    function category(){
       return $this->belongsTo('App\Category');
   }

    // relateion to get user who create ot update post
    function user(){
        return $this->belongsTo('App\User');
    }


}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


class PostController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //validate Data
        $request->validate([
            'category_id' => 'nullable|int|exists:categories,id'
        ]);

        $data = Post::with(['user', 'category'])
            ->orderBy('id', 'DESC');

        if($request->category_id){
            $data->where('category_id',$request->category_id);
        }

        /***
         * it's better if make it server DataTable  :)
         * and make limit from setting :)
         */
        $data = $data->paginate(10);

        return view('admin.post.index', ['data' => $data]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::select('id','title')->get();
        return view('admin.post.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate Data
        $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
            'category_id' => 'required|int|exists:categories,id',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        // uniq name for image
        $imageName = time().uniqid() . '.' . request()->image->getClientOriginalExtension();
        request()->image->move(public_path('uploads/post'), $imageName);

        $store = Post::create([
            'title' => $request['title'],
            'content' => $request['content'],
            'category_id' => $request['category_id'],
            'user_id' => Auth::id(),
            'image' => $imageName
        ]);

        if ($store) {
            $store->update(['slug'=>slug($store->title,$store->id)]);
            return redirect()
                ->route('admin.post.create')
                ->with('status', 'success')
                ->with('msg', 'Data has been added successfully');
        } else {
            return redirect()
                ->route('admin.post.create')
                ->with('status', 'danger')
                ->with('msg', 'Sorry Couldn\'t add ');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::select('id','title')->get();
        return view('admin.post.create', ['data' => $post,'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //validate data
        $validation = [
            'title' => 'required|string|max:255',
            'content' => 'required|string',
            'category_id' => 'required|int|exists:categories,id'
        ];

        if ($request->image) {
            $validation['image'] = 'required|image|mimes:jpeg,png,jpg,gif,svg|';
        }

        $request->validate($validation);
        if ($request->image) {
            // uniq name for image
            $imageName = time().uniqid() . '.' . request()->image->getClientOriginalExtension();
            request()->image->move(public_path('uploads/post'), $imageName);
        }

        $data = [
            'title' => $request['title'],
            'content' => $request['content'],
            'category_id' => $request['category_id'],
            'user_id' => Auth::id(),
            'slug' => slug($request['title'],$post->id)
        ];

        if ($request->image) {
            $data['image'] = $imageName;
        }

        $update = $post->update($data);

        //check query
        if ($update) {
            return redirect()
                ->route('admin.post.edit', $post->id)
                ->with('status', 'success')
                ->with('msg', 'Data has been Updated successfully');
        } else {
            return redirect()
                ->route('admin.post.edit', $post->id)
                ->with('status', 'danger')
                ->with('msg', 'Sorry Couldn\'t Updated');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {

        // delete comments of post
        $post->comments()->delete();

        // delete post
        if ($post->delete()) {
            return ['status' => true, 'msg' => __('News has been deleted successfully')];
        } else {
            return ['status' => false, 'msg' => 'Sorry Couldn\'t Delete'];
        }
    }

}

resources/views/admin/post/create.blade.php
@extends('layouts.main')

@section('content')
    <section class="blog-area section">
        <div class="container">
    <div class="row">
        <div class="col-md-12 post-wrapper">

            @if($errors->any())
                <div class="col-sm-12">
                    <div class="card">
                        <div class="alert alert-danger">
                            {{__('Some fields are invalid please fix them')}}
                        </div>
                    </div>
                </div>
            @elseif(Session::has('status'))
                <div class="col-sm-12">
                    <div class="card">
                        <div class="alert alert-{{Session::get('status')}}">
                            {{ Session::get('msg') }}
                        </div>
                    </div>
                </div>
            @endif
            {!! Form::open(['route' => isset($data->id) ? ['admin.post.update',$data->id]:'admin.post.store','method' => isset($data->id) ?  'PATCH' : 'POST','files' => true]) !!}

                <div class="form-group col-sm-12{!! formError($errors,'category_id',true) !!}">
                    <div class="controls">
                        {!! Form::label('category_id','Category') !!}
                        {!! Form::select('category_id',[''=>'Select Category']+array_column($categories->toArray(),'title','id'),isset($data->id) ? $data->category_id:old('category_id'),['class'=>'form-control']) !!}
                    </div>
                    {!! formError($errors,'category_id') !!}
                </div>


                <div class="form-group col-sm-12{!! formError($errors,'title',true) !!}">
                    <div class="controls">
                        {!! Form::label('title','Title') !!}
                        {!! Form::text('title',isset($data->id) ? $data->title:old('title'),['class'=>'form-control']) !!}
                    </div>
                    {!! formError($errors,'title') !!}
                </div>

                <div class="form-group col-sm-12{!! formError($errors,'image',true) !!}">
                    <div class="controls">
                        {!! Form::label('image','Image') !!}
                        {!! Form::file('image',['class'=>'form-control']) !!}
                    </div>
                    {!! formError($errors,'image') !!}
                </div>

                @if(isset($data->id))
                    <div class="form-group col-sm-12">
                        <img style="width: 60px;height: 60px" src="{{asset('uploads/post/'.$data->image)}}" alt="">
                    </div>
                @endif

                <div class="form-group col-sm-12{!! formError($errors,'content',true) !!}">
                    <div class="controls">
                        {!! Form::label('content','Content') !!}
                        {!! Form::textarea('content',isset($data->id) ? $data->content:old('content'),['class'=>'form-control']) !!}
                    </div>
                    {!! formError($errors,'content') !!}
                </div>






                {!! Form::submit(__('Save'),['class'=>'btn btn-success pull-right']) !!}
                {!! Form::close() !!}


        </div>
    </div><!-- row -->
        </div><!-- container -->
    </section><!-- section -->
@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.main')

@section('content')
    <section class="blog-area section">
        <div class="container">
    <div class="row">
        <div class="col-md-12 post-wrapper">
            <a href="{{route('admin.post.create')}}" class="btn btn-primary mb-2">Add New</a>
            <table class="table">
                <thead class="thead-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Category</th>
                    <th scope="col">Title</th>
                    <th scope="col">Image</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                @if($data->isNotEmpty())
                    @foreach($data as $row)
                        <tr>
                            <th scope="row">{{$row->id}}</th>
                            <th scope="row">{{$row->category->title}}</th>
                            <td>{{$row->title}}</td>
                            <td><img src="{{asset('uploads/post/'.$row->image)}}" style="width: 60px;height: 60px" /></td>
                            <td>{{$row->user->name}}</td>
                            <td><a href="{{route('admin.post.edit',$row->id)}}" class="btn btn-primary"><i class="fa fa-edit" aria-hidden="true"></i></a></td>
                            <td><a href="javascript:;" onclick="deleteRecord('{{route('admin.post.destroy',$row->id)}}')" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a></td>


                        </tr>
                    @endforeach
                @else
                <tr><td colspan="4">There is no Data</td></tr>
                @endif
                </tbody>
            </table>
            {{ $data->links() }}

        </div>
    </div><!-- row -->
        </div><!-- container -->
    </section><!-- section -->
@endsection