routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::get('/', 'HomeController@index')->name('home');
Route::get('/details/{slug}', 'HomeController@details')->name('details');
Route::post('/comment', 'HomeController@comment')->name('comment');

Route::group(['prefix'=>'admin'],function(){
    Auth::routes();

    Route::get('/','CategoryController@index');
    Route::resource('/category', 'CategoryController',['as'=>'admin']);
    Route::resource('/post', 'PostController',['as'=>'admin']);
    Route::get('logout', 'Auth\LoginController@logout', function () {
        return abort(404);
    })->name('logout');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE HTML>
<html lang="en">
<head>
	<title>Laravel Blog</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">

	<meta name="csrf-token" content="{{ csrf_token() }}">
	<!-- Font -->

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">


	<!-- Stylesheets -->
	<link href="{{asset('assets/common-css/bootstrap.css')}}" rel="stylesheet">
	<link href="{{asset('assets/common-css/swiper.css')}}" rel="stylesheet">
	<link href="{{asset('assets/common-css/ionicons.css')}}" rel="stylesheet">
	<link href="{{asset('assets/blank-static/css/styles.css')}}" rel="stylesheet">
	<link href="{{asset('assets/blank-static/css/responsive.css')}}" rel="stylesheet">

	@yield('header')
</head>
<body >

	<header>
		<div class="container-fluid position-relative no-side-padding">

			<a href="{{route('home')}}" class="logo"><img src="{{asset('assets/images/logo.png')}}" alt="Logo Image"></a>

			<div class="menu-nav-icon" data-nav-menu="#main-menu"><i class="ion-navicon"></i></div>


			<ul class="main-menu visible-on-click" id="main-menu">
				@if(Auth::check())
				<li><a href="javascript:;">Hello  {{ Auth::user()->name }}</a></li>
				<li><a href="{{route('admin.category.index')}}">Categories</a></li>
				<li><a href="{{route('admin.post.index')}}">Posts</a></li>
				<li><a href="{{route('logout',Auth::user()->id)}}">Logout</a></li>

				@endif
			</ul><!-- main-menu -->

			<div class="src-area">
				<form method="get" action="{{route('home')}}" >
					<button class="src-btn" type="submit"><i class="ion-ios-search-strong"></i></button>
					<input name="word" class="src-input" type="text" placeholder="Type of search">
				</form>
			</div>


		</div><!-- conatiner -->
	</header>




			@yield('content')




	<footer>
		<div class="container">
			<div class="row">

				<div class="col-lg-12 col-md-6">
					<div class="footer-section">

						<a class="logo" href="#"><img src="{{asset('assets/images/logo.png')}}" alt="Logo Image"></a>
						<p class="copyright">Bona @ 2017. All rights reserved.</p>
						<p class="copyright">Designed by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>

					</div><!-- footer-section -->
				</div><!-- col-lg-4 col-md-6 -->



			</div><!-- row -->
		</div><!-- container -->
	</footer>


	<!-- SCIPTS -->


	<script src="{{asset('assets/common-js/jquery-3.1.1.min.js')}}"></script>

	<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

	<script src="{{asset('assets/common-js/tether.min.js')}}"></script>

	<script src="{{asset('assets/common-js/bootstrap.js')}}"></script>

	<script src="{{asset('assets/common-js/swiper.js')}}"></script>

	<script src="{{asset('assets/common-js/scripts.js')}}"></script>
	<script>
        function deleteRecord($routeName,$reload){

            if(!confirm("Do you want to delete this ?")){
                return false;
            }

            if($reload == undefined){
                $reload = 3000;
            }

            $.post(
                $routeName,
                {
                    '_method':'DELETE',
                    '_token':$('meta[name="csrf-token"]').attr('content')
                },
                function(response){


                        $data = response;
                        if($data.status == true){
                            toastr.success($data.msg, 'Success !', {"closeButton": true});
                            if($reload){
                                setTimeout(function(){location.reload();},$reload);
                            }
                        }else{
                            toastr.error($data.msg, 'Error !', {"closeButton": true});
                        }

                }
            )
        }
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
	</script>

	@yield('footer')
</body>
</html>